/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author hp
 */
public class AdminRegistration extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminRegistration.class.getName());

    /**
     * Creates new form Login
     */
    public AdminRegistration() {
        initComponents();
        setSize(1000,564);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        Registration = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        Phone = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        register = new javax.swing.JButton();
        formBackground = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SignupIcon.png"))); // NOI18N
        getContentPane().add(icon);
        icon.setBounds(405, 110, 40, 40);

        Registration.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        Registration.setForeground(new java.awt.Color(102, 102, 102));
        Registration.setText("Add Admin");
        getContentPane().add(Registration);
        Registration.setBounds(450, 110, 140, 40);

        Name.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Name.setForeground(new java.awt.Color(95, 95, 95));
        Name.setText("Full Name");
        getContentPane().add(Name);
        Name.setBounds(390, 170, 60, 16);

        name.setForeground(new java.awt.Color(102, 102, 102));
        name.setText("Enter The Name");
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 95, 95)));
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addActionListener(this::nameActionPerformed);
        getContentPane().add(name);
        name.setBounds(390, 190, 220, 18);

        Email.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Email.setForeground(new java.awt.Color(95, 95, 95));
        Email.setText("Email");
        getContentPane().add(Email);
        Email.setBounds(390, 220, 40, 16);

        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setText("Enter The Email");
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 95, 95)));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(this::emailActionPerformed);
        getContentPane().add(email);
        email.setBounds(390, 240, 220, 18);

        Phone.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Phone.setForeground(new java.awt.Color(95, 95, 95));
        Phone.setText("Phone");
        getContentPane().add(Phone);
        Phone.setBounds(390, 270, 40, 16);

        phone.setForeground(new java.awt.Color(102, 102, 102));
        phone.setText("Enter The Phone");
        phone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 95, 95)));
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });
        phone.addActionListener(this::phoneActionPerformed);
        getContentPane().add(phone);
        phone.setBounds(390, 290, 220, 18);

        Address.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Address.setForeground(new java.awt.Color(95, 95, 95));
        Address.setText("Address");
        getContentPane().add(Address);
        Address.setBounds(390, 320, 50, 16);

        address.setForeground(new java.awt.Color(102, 102, 102));
        address.setText("Enter The Address");
        address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 95, 95)));
        address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFocusLost(evt);
            }
        });
        address.addActionListener(this::addressActionPerformed);
        getContentPane().add(address);
        address.setBounds(390, 340, 220, 18);

        Password.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Password.setForeground(new java.awt.Color(95, 95, 95));
        Password.setText("Password");
        getContentPane().add(Password);
        Password.setBounds(390, 370, 60, 16);

        password.setForeground(new java.awt.Color(102, 102, 102));
        password.setText("Enter The Password");
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 95, 95)));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addActionListener(this::passwordActionPerformed);
        getContentPane().add(password);
        password.setBounds(390, 390, 220, 18);

        register.setBackground(new java.awt.Color(0, 0, 204));
        register.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        register.setText("Register");
        register.addActionListener(this::registerActionPerformed);
        getContentPane().add(register);
        register.setBounds(450, 430, 83, 29);

        formBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SignupBackground.png"))); // NOI18N
        formBackground.setMaximumSize(new java.awt.Dimension(259, 259));
        formBackground.setMinimumSize(new java.awt.Dimension(259, 259));
        formBackground.setPreferredSize(new java.awt.Dimension(259, 259));
        getContentPane().add(formBackground);
        formBackground.setBounds(370, 90, 260, 400);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SignBackground.jpg"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(1000, 564));
        background.setMinimumSize(new java.awt.Dimension(1000, 564));
        background.setPreferredSize(new java.awt.Dimension(1000, 564));
        getContentPane().add(background);
        background.setBounds(0, 0, 1000, 564);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // Remove placeholder
        if(name.getText().trim().equals("Enter The Name")) {
            name.setText("");
        }
    }//GEN-LAST:event_nameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        // Add placeholder
        if(name.getText().trim().equals("")) {
            name.setText("Enter The Name");
        }
    }//GEN-LAST:event_nameFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // Remove placeholder
        if(email.getText().trim().equals("Enter The Email")) {
            email.setText("");
        }
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // Add placeholder
        if(email.getText().trim().equals("")) {
            email.setText("Enter The Email");
        }
    }//GEN-LAST:event_emailFocusLost

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        // Remove placeholder
        if(phone.getText().trim().equals("Enter The Phone")) {
            phone.setText("");
        }
    }//GEN-LAST:event_phoneFocusGained

    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost
        // Add placeholder
        if(phone.getText().trim().equals("")) {
            phone.setText("Enter The Phone");
        }
    }//GEN-LAST:event_phoneFocusLost

    private void addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusGained
        // Remove placeholder
        if(address.getText().trim().equals("Enter The Address")) {
            address.setText("");
        }
    }//GEN-LAST:event_addressFocusGained

    private void addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusLost
        // Add placeholder
        if(address.getText().trim().equals("")) {
            address.setText("Enter The Address");
        }
    }//GEN-LAST:event_addressFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // Remove placeholder
        if(password.getText().trim().equals("Enter The Password")) {
            password.setText("");
        }
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // Add placeholder
        if(password.getText().trim().equals("")) {
            password.setText("Enter The Password");
        }
    }//GEN-LAST:event_passwordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminRegistration().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel Registration;
    private javax.swing.JTextField address;
    private javax.swing.JLabel background;
    private javax.swing.JTextField email;
    private javax.swing.JLabel formBackground;
    private javax.swing.JLabel icon;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
    
    public void AddAdminListener(ActionListener listener) {
        register.addActionListener(listener);
    }
    
    public javax.swing.JTextField getname(){
        return name;
    }
    
    public javax.swing.JTextField getemail(){
        return email;
    }
    
    public javax.swing.JTextField getphone(){
        return phone;
    }
    
    public javax.swing.JTextField getaddress(){
        return address;
    }
    
    public javax.swing.JPasswordField getpassword(){
        return password;
    }
}