/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Asus
 */
public class BookingPassenger extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingPassenger.class.getName());

    /**
     * Creates new form PassengerDashboard_Mybookings
     */
    public BookingPassenger() {
        initComponents();
        this.setLocationRelativeTo(null); // centers the window
    this.setVisible(true); // makes sure it shows
    this.toFront();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Allbooking = new javax.swing.JButton();
        Mybookings = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        picture = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        PassDash = new javax.swing.JLabel();
        managetrips = new javax.swing.JLabel();
        Searchtrips = new javax.swing.JButton();
        mybookings = new javax.swing.JButton();
        Allbooking = new javax.swing.JButton();
        pending = new javax.swing.JButton();
        boarded = new javax.swing.JButton();
        completedbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Minibus.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel2.setText("Bato+");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile.png"))); // NOI18N
        jButton1.setBorder(null);
        picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Minibus.png"))); // NOI18N

        logo.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        logo.setText("Bato+");

        loginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile.png"))); // NOI18N
        loginbtn.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 966, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addComponent(picture)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 966, Short.MAX_VALUE)
                .addComponent(loginbtn)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel2))))
                        .addComponent(picture))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginbtn)
                            .addComponent(logo))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 100);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setText("Passenger Dashboard");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 320, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Manage Trips");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 180, 110, 21);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Search Trips");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 220, 140, 32);

        jButton3.setBackground(new java.awt.Color(0, 51, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("My Bookings");
        getContentPane().add(jButton3);
        jButton3.setBounds(180, 220, 150, 30);
        PassDash.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        PassDash.setText("Passenger Dashboard");
        getContentPane().add(PassDash);
        PassDash.setBounds(20, 130, 320, 50);

        managetrips.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        managetrips.setForeground(new java.awt.Color(153, 153, 153));
        managetrips.setText("Manage Trips");
        getContentPane().add(managetrips);
        managetrips.setBounds(20, 180, 110, 21);

        Searchtrips.setBackground(new java.awt.Color(204, 204, 204));
        Searchtrips.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Searchtrips.setForeground(new java.awt.Color(102, 102, 102));
        Searchtrips.setText("Search Trips");
        Searchtrips.addActionListener(this::SearchtripsActionPerformed);
        getContentPane().add(Searchtrips);
        Searchtrips.setBounds(20, 220, 140, 32);

        mybookings.setBackground(new java.awt.Color(0, 51, 255));
        mybookings.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mybookings.setForeground(new java.awt.Color(255, 255, 255));
        mybookings.setText("My Bookings");
        getContentPane().add(mybookings);
        mybookings.setBounds(180, 220, 150, 30);

        Allbooking.setBackground(new java.awt.Color(0, 51, 255));
        Allbooking.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Allbooking.setForeground(new java.awt.Color(255, 255, 255));
        Allbooking.setText("All");
        getContentPane().add(Allbooking);
        Allbooking.setBounds(20, 290, 60, 27);

        Mybookings.setBackground(new java.awt.Color(204, 204, 204));
        Mybookings.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Mybookings.setForeground(new java.awt.Color(102, 102, 102));
        Mybookings.setText("Pending");
        getContentPane().add(Mybookings);
        Mybookings.setBounds(100, 290, 110, 30);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setText("Boarded");
        getContentPane().add(jButton4);
        jButton4.setBounds(230, 290, 120, 30);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 102, 102));
        jButton5.setText("Completed");
        getContentPane().add(jButton5);
        jButton5.setBounds(370, 290, 140, 30);
        pending.setBackground(new java.awt.Color(204, 204, 204));
        pending.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pending.setForeground(new java.awt.Color(102, 102, 102));
        pending.setText("Pending");
        getContentPane().add(pending);
        pending.setBounds(100, 290, 110, 30);

        boarded.setBackground(new java.awt.Color(204, 204, 204));
        boarded.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boarded.setForeground(new java.awt.Color(102, 102, 102));
        boarded.setText("Boarded");
        getContentPane().add(boarded);
        boarded.setBounds(230, 290, 120, 30);

        completedbtn.setBackground(new java.awt.Color(204, 204, 204));
        completedbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        completedbtn.setForeground(new java.awt.Color(102, 102, 102));
        completedbtn.setText("Completed");
        getContentPane().add(completedbtn);
        completedbtn.setBounds(370, 290, 140, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nobookingfound.png"))); // NOI18N
        jLabel6.setText("No Bookings Found");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(556, 556, 556)
                .addComponent(jLabel6)
                .addContainerGap(553, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 360, 1230, 260);

        setBounds(1280, 740, 1282, 740);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    private void SearchtripsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchtripsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchtripsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookingPassenger().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Allbooking;
    private javax.swing.JButton Mybookings;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel PassDash;
    private javax.swing.JButton Searchtrips;
    private javax.swing.JButton boarded;
    private javax.swing.JButton completedbtn;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel managetrips;
    private javax.swing.JButton mybookings;
    private javax.swing.JButton pending;
    private javax.swing.JLabel picture;
    // End of variables declaration//GEN-END:variables
}
