/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Nitro V 16
 */
public class Booking extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Booking.class.getName());

    /**
     * Creates new form Driver_Ongoing
     */
    public Booking() {
        initComponents();
        setSize(1280, 740);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        Bato = new javax.swing.JLabel();
        profile = new javax.swing.JButton();
        PassengerDashboard = new javax.swing.JLabel();
        intro = new javax.swing.JLabel();
        searchtrips = new javax.swing.JButton();
        Mybookings = new javax.swing.JButton();
        ongoing = new javax.swing.JButton();
        completed = new javax.swing.JButton();
        ongoing1 = new javax.swing.JButton();
        Mybookings1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        header.setPreferredSize(new java.awt.Dimension(1280, 740));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        Bato.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        Bato.setText("Bato+");
        Bato.setMaximumSize(new java.awt.Dimension(117, 47));
        Bato.setMinimumSize(new java.awt.Dimension(117, 47));

        profile.setBackground(new java.awt.Color(244, 244, 244));
        profile.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        profile.setForeground(new java.awt.Color(102, 102, 102));
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile.png"))); // NOI18N
        profile.setBorder(null);
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(Bato, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 969, Short.MAX_VALUE)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addComponent(Bato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(header);
        header.setBounds(0, 0, 1270, 90);

        PassengerDashboard.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        PassengerDashboard.setText("Passenger Dashboard");
        getContentPane().add(PassengerDashboard);
        PassengerDashboard.setBounds(50, 100, 330, 41);

        intro.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        intro.setForeground(new java.awt.Color(153, 153, 153));
        intro.setText("Manage trips.");
        getContentPane().add(intro);
        intro.setBounds(50, 150, 210, 21);

        searchtrips.setBackground(new java.awt.Color(204, 204, 204));
        searchtrips.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchtrips.setForeground(new java.awt.Color(102, 102, 102));
        searchtrips.setText("Search Trips");
        searchtrips.addActionListener(this::searchtripsActionPerformed);
        getContentPane().add(searchtrips);
        searchtrips.setBounds(50, 190, 150, 32);

        Mybookings.setBackground(new java.awt.Color(51, 102, 255));
        Mybookings.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mybookings.setForeground(new java.awt.Color(255, 255, 255));
        Mybookings.setText("All");
        getContentPane().add(Mybookings);
        Mybookings.setBounds(50, 270, 70, 32);

        ongoing.setBackground(new java.awt.Color(204, 204, 204));
        ongoing.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ongoing.setForeground(new java.awt.Color(102, 102, 102));
        ongoing.setText("Pending");
        getContentPane().add(ongoing);
        ongoing.setBounds(150, 270, 100, 32);

        completed.setBackground(new java.awt.Color(204, 204, 204));
        completed.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        completed.setForeground(new java.awt.Color(102, 102, 102));
        completed.setText("Completed");
        completed.addActionListener(this::completedActionPerformed);
        getContentPane().add(completed);
        completed.setBounds(410, 270, 120, 32);

        ongoing1.setBackground(new java.awt.Color(204, 204, 204));
        ongoing1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ongoing1.setForeground(new java.awt.Color(102, 102, 102));
        ongoing1.setText("Boarded");
        getContentPane().add(ongoing1);
        ongoing1.setBounds(280, 270, 97, 32);

        Mybookings1.setBackground(new java.awt.Color(51, 102, 255));
        Mybookings1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mybookings1.setForeground(new java.awt.Color(255, 255, 255));
        Mybookings1.setText("My Bookings");
        getContentPane().add(Mybookings1);
        Mybookings1.setBounds(230, 190, 150, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nobookingfound.png"))); // NOI18N
        jLabel1.setText("No Bookings Found.");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(484, 484, 484)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(549, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 370, 1180, 230);

        setSize(new java.awt.Dimension(1280, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchtripsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtripsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtripsActionPerformed

    private void completedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Booking().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bato;
    private javax.swing.JButton Mybookings;
    private javax.swing.JButton Mybookings1;
    private javax.swing.JLabel PassengerDashboard;
    private javax.swing.JButton completed;
    private javax.swing.JPanel header;
    private javax.swing.JLabel intro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton ongoing;
    private javax.swing.JButton ongoing1;
    private javax.swing.JButton profile;
    private javax.swing.JButton searchtrips;
    // End of variables declaration//GEN-END:variables
}
