/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Nitro V 16
 */
public class MyBooking extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MyBooking.class.getName());
    private int userId;

    /**
     * Creates new form Driver_Ongoing
     */
    public MyBooking() {
        initComponents();
        setSize(1280, 740);
        bookingDAO = new BookingDAO();
        // Default userId to 1 for testing if not set, or leave it and wait for setter
         this.userId = 1; 
         loadBookings(); 
    }

    public void setUserId(int userId) {
        this.userId = userId;
        loadBookings();
    }
    
    public void loadBookings() {
        if (userId == 0) {
            // Try to load for user 1 just in case it's a test run
            // Or just return
            // System.out.println("User ID not set for MyBooking");
             this.userId = 1; // Fallback for testing as per user request context "I have booked..."
        }
        
        List<Booking> bookings = bookingDAO.getUserBookings(userId);
        DefaultTableModel model = (DefaultTableModel) MyBookingTable.getModel();
        model.setRowCount(0); // Clear existing data
        
        if (bookings.isEmpty()) {
            noData.setVisible(true);
        } else {
            noData.setVisible(false);
            for (Booking b : bookings) {
                model.addRow(new Object[]{
                    b.getOrigin(),
                    b.getDestination(),
                    b.getTotalFare(),
                    b.getBookingToken(),
                    b.getStatus()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        Bato = new javax.swing.JLabel();
        profile = new javax.swing.JButton();
        PassengerDashboard = new javax.swing.JLabel();
        intro = new javax.swing.JLabel();
        searchtrips = new javax.swing.JButton();
        all = new javax.swing.JButton();
        pending = new javax.swing.JButton();
        completed = new javax.swing.JButton();
        boarded = new javax.swing.JButton();
        Mybookings = new javax.swing.JButton();
        noData = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        MyBookingTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        header.setPreferredSize(new java.awt.Dimension(1280, 740));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        Bato.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        Bato.setText("Bato+");
        Bato.setMaximumSize(new java.awt.Dimension(117, 47));
        Bato.setMinimumSize(new java.awt.Dimension(117, 47));

        profile.setBackground(new java.awt.Color(244, 244, 244));
        profile.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        profile.setForeground(new java.awt.Color(102, 102, 102));
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile.png"))); // NOI18N
        profile.setBorder(null);
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(Bato, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 969, Short.MAX_VALUE)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addComponent(Bato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(header);
        header.setBounds(0, 0, 1270, 90);

        PassengerDashboard.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        PassengerDashboard.setText("Passenger Dashboard");
        getContentPane().add(PassengerDashboard);
        PassengerDashboard.setBounds(50, 100, 330, 41);

        intro.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        intro.setForeground(new java.awt.Color(153, 153, 153));
        intro.setText("Manage trips.");
        getContentPane().add(intro);
        intro.setBounds(50, 150, 210, 21);

        searchtrips.setBackground(new java.awt.Color(204, 204, 204));
        searchtrips.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchtrips.setForeground(new java.awt.Color(102, 102, 102));
        searchtrips.setText("Search Trips");
        searchtrips.addActionListener(this::searchtripsActionPerformed);
        getContentPane().add(searchtrips);
        searchtrips.setBounds(50, 190, 150, 36);

        all.setBackground(new java.awt.Color(51, 102, 255));
        all.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        all.setForeground(new java.awt.Color(255, 255, 255));
        all.setText("All");
        getContentPane().add(all);
        all.setBounds(50, 270, 70, 36);

        pending.setBackground(new java.awt.Color(204, 204, 204));
        pending.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pending.setForeground(new java.awt.Color(102, 102, 102));
        pending.setText("Pending");
        getContentPane().add(pending);
        pending.setBounds(150, 270, 100, 36);

        completed.setBackground(new java.awt.Color(204, 204, 204));
        completed.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        completed.setForeground(new java.awt.Color(102, 102, 102));
        completed.setText("Completed");
        completed.addActionListener(this::completedActionPerformed);
        getContentPane().add(completed);
        completed.setBounds(410, 270, 122, 36);

        boarded.setBackground(new java.awt.Color(204, 204, 204));
        boarded.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boarded.setForeground(new java.awt.Color(102, 102, 102));
        boarded.setText("Boarded");
        getContentPane().add(boarded);
        boarded.setBounds(280, 270, 101, 36);

        Mybookings.setBackground(new java.awt.Color(51, 102, 255));
        Mybookings.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mybookings.setForeground(new java.awt.Color(255, 255, 255));
        Mybookings.setText("My Bookings");
        getContentPane().add(Mybookings);
        Mybookings.setBounds(230, 190, 150, 36);

        noData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noData.setForeground(new java.awt.Color(153, 153, 153));
        noData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nobookingfound.png"))); // NOI18N
        noData.setText("No Bookings Found.");
        noData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        noData.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(noData);
        noData.setBounds(520, 520, 147, 87);

        MyBookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Origin", "Destination", "Fare", "Token Number", "Status"
            }
        ));
        scroll.setViewportView(MyBookingTable);

        getContentPane().add(scroll);
        scroll.setBounds(40, 350, 1180, 340);

        setSize(new java.awt.Dimension(1280, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchtripsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtripsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtripsActionPerformed

    private void completedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MyBooking().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bato;
    private javax.swing.JTable MyBookingTable;
    private javax.swing.JButton Mybookings;
    private javax.swing.JLabel PassengerDashboard;
    private javax.swing.JButton all;
    private javax.swing.JButton boarded;
    private javax.swing.JButton completed;
    private javax.swing.JPanel header;
    private javax.swing.JLabel intro;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel noData;
    private javax.swing.JButton pending;
    private javax.swing.JButton profile;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JButton searchtrips;
    // End of variables declaration//GEN-END:variables
    public void AllListener(ActionListener listener) {
        all.addActionListener(listener);
    }
    
    public void PendingListener(ActionListener listener) {
        pending.addActionListener(listener);
    }
    
    public void BoardedListener(ActionListener listener) {
        boarded.addActionListener(listener);
    }
    
    public void CompletedListener(ActionListener listener) {
        completed.addActionListener(listener);
    }
    
    public void SearchTripsListener(ActionListener listener) {
        searchtrips.addActionListener(listener);
    }
    
    public void ProfileListener(ActionListener listener) {
        profile.addActionListener(listener);
    }
    
    public javax.swing.JButton getAllButton() {
        return all;
    }
    
    public javax.swing.JButton getPendingButton() {
        return pending;
    }
    
    public javax.swing.JButton getCompletedButton() {
        return completed;
    }
    
    public javax.swing.JButton getBoardedButton() {
        return boarded;
    }
    
    public javax.swing.JButton getSearchTripsButton() {
        return searchtrips;
    }
    
    public javax.swing.JButton getProfileButton() {
        return profile;
    }
    
    public JScrollPane getScrollPane() {
        return scroll;
    }
    
    public JTable getResultTable() {
        return MyBookingTable;
    }
    
    public JLabel getNoData() {
        return noData;
    }
}