/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author Nitro V 16
 */
public class Notification extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Notification.class.getName());

    /**
     * Creates new form Notification
     */
    public Notification() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        Bato = new javax.swing.JLabel();
        AdminDashboard = new javax.swing.JLabel();
        intro = new javax.swing.JLabel();
        vehicles = new javax.swing.JButton();
        routes = new javax.swing.JButton();
        trips = new javax.swing.JButton();
        users = new javax.swing.JButton();
        notifications = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        form = new javax.swing.JPanel();
        NotificationCenter = new javax.swing.JLabel();
        summary = new javax.swing.JLabel();
        Trips = new javax.swing.JLabel();
        trip = new javax.swing.JComboBox<>();
        Notifications = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        Messages = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        send = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        Bato.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        Bato.setText("Bato+");
        Bato.setMaximumSize(new java.awt.Dimension(117, 47));
        Bato.setMinimumSize(new java.awt.Dimension(117, 47));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(Bato, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1065, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addComponent(Bato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        AdminDashboard.setBackground(new java.awt.Color(255, 255, 255));
        AdminDashboard.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        AdminDashboard.setText("Admin Dashboard");
        AdminDashboard.setMaximumSize(new java.awt.Dimension(356, 47));
        AdminDashboard.setMinimumSize(new java.awt.Dimension(356, 47));
        getContentPane().add(AdminDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        intro.setBackground(new java.awt.Color(153, 153, 153));
        intro.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        intro.setForeground(new java.awt.Color(153, 153, 153));
        intro.setText("Manage vehicles, routes, trips, and users");
        getContentPane().add(intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        vehicles.setBackground(new java.awt.Color(244, 244, 244));
        vehicles.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        vehicles.setForeground(new java.awt.Color(102, 102, 102));
        vehicles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vehicleIcon.png"))); // NOI18N
        vehicles.setText("Vehicles");
        vehicles.setBorder(null);
        vehicles.setBorderPainted(false);
        vehicles.setContentAreaFilled(false);
        getContentPane().add(vehicles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        routes.setBackground(new java.awt.Color(244, 244, 244));
        routes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        routes.setForeground(new java.awt.Color(102, 102, 102));
        routes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/routeIcon.png"))); // NOI18N
        routes.setText("Routes");
        routes.setBorder(null);
        routes.setBorderPainted(false);
        routes.setContentAreaFilled(false);
        routes.addActionListener(this::routesActionPerformed);
        getContentPane().add(routes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, 20));

        trips.setBackground(new java.awt.Color(244, 244, 244));
        trips.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        trips.setForeground(new java.awt.Color(102, 102, 102));
        trips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tripIcon.png"))); // NOI18N
        trips.setText("Trips");
        trips.setBorder(null);
        trips.setBorderPainted(false);
        trips.setContentAreaFilled(false);
        trips.addActionListener(this::tripsActionPerformed);
        getContentPane().add(trips, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        users.setBackground(new java.awt.Color(244, 244, 244));
        users.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        users.setForeground(new java.awt.Color(102, 102, 102));
        users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userIcon.png"))); // NOI18N
        users.setText("Users");
        users.setBorder(null);
        users.setBorderPainted(false);
        users.setContentAreaFilled(false);
        getContentPane().add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        notifications.setBackground(new java.awt.Color(244, 244, 244));
        notifications.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        notifications.setForeground(new java.awt.Color(36, 87, 197));
        notifications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bell.png"))); // NOI18N
        notifications.setText("Notifications");
        notifications.setBorder(null);
        notifications.setBorderPainted(false);
        notifications.setContentAreaFilled(false);
        getContentPane().add(notifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        separator.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 1210, 10));

        form.setBackground(new java.awt.Color(255, 255, 255));

        NotificationCenter.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        NotificationCenter.setText("Notification Center");

        summary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        summary.setForeground(new java.awt.Color(153, 153, 153));
        summary.setText("Send notifications to passengers about trip updates");

        Trips.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Trips.setForeground(new java.awt.Color(102, 102, 102));
        Trips.setText("Select Trips");

        trip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        trip.setForeground(new java.awt.Color(153, 153, 153));
        trip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the Trip" }));

        Notifications.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Notifications.setForeground(new java.awt.Color(102, 102, 102));
        Notifications.setText("Notifications Tab");

        type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        type.setForeground(new java.awt.Color(153, 153, 153));
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Notification Type", "General", "Rescheduled", "Cancelled", "Route Chnage" }));

        Messages.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Messages.setForeground(new java.awt.Color(102, 102, 102));
        Messages.setText("Message");

        message.setColumns(20);
        message.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        message.setForeground(new java.awt.Color(153, 153, 153));
        message.setRows(5);
        message.setText("Enter your message here");
        message.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                messageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                messageFocusLost(evt);
            }
        });
        scroll.setViewportView(message);

        send.setBackground(new java.awt.Color(0, 0, 204));
        send.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        send.setForeground(new java.awt.Color(255, 255, 255));
        send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mynaui_send.png"))); // NOI18N
        send.setText("Send Notification");
        send.addActionListener(this::sendActionPerformed);

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(send)
                    .addComponent(NotificationCenter)
                    .addComponent(summary)
                    .addComponent(Trips)
                    .addComponent(trip, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Notifications)
                    .addComponent(type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Messages)
                    .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 1129, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(NotificationCenter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(summary)
                .addGap(18, 18, 18)
                .addComponent(Trips)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Notifications)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Messages)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(form, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 1220, 430));

        setBounds(0, 0, 1280, 740);
    }// </editor-fold>//GEN-END:initComponents

    private void tripsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tripsActionPerformed

    private void routesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routesActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendActionPerformed

    private void messageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messageFocusGained
        // Removes placeholder
        if (message.getText().equals("Enter your message here")) {
            message.setText("");
        }
    }//GEN-LAST:event_messageFocusGained

    private void messageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messageFocusLost
        // Adds placeholder
        if (message.getText().equals("")) {
            message.setText("Enter your message here");
        }
    }//GEN-LAST:event_messageFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Notification().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDashboard;
    private javax.swing.JLabel Bato;
    private javax.swing.JLabel Messages;
    private javax.swing.JLabel NotificationCenter;
    private javax.swing.JLabel Notifications;
    private javax.swing.JLabel Trips;
    private javax.swing.JPanel form;
    private javax.swing.JPanel header;
    private javax.swing.JLabel intro;
    private javax.swing.JLabel logo;
    private javax.swing.JTextArea message;
    private javax.swing.JButton notifications;
    private javax.swing.JButton routes;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JButton send;
    private javax.swing.JSeparator separator;
    private javax.swing.JLabel summary;
    private javax.swing.JComboBox<String> trip;
    private javax.swing.JButton trips;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JButton users;
    private javax.swing.JButton vehicles;
    // End of variables declaration//GEN-END:variables

    // What happens when user clicks button
    public void SendNotificationListener(ActionListener listener) {
        send.addActionListener(listener);
    }
    
    public void VehicleManagementListener(ActionListener listener) {
        vehicles.addActionListener(listener);
    }
        
    public void RouteManagementListener(ActionListener listener) {
        routes.addActionListener(listener);
    }
    
    public void TripManagementListener(ActionListener listener) {
        trips.addActionListener(listener);
    }

    public void UserManagementListener(ActionListener listener) {
        users.addActionListener(listener);
    }
    
    
    // Read / Manipulate value entered by user
    public javax.swing.JComboBox getTrip() {
        return trip;
    }
    
    public javax.swing.JComboBox getGenre() {
        return type;
    }
    
    public javax.swing.JTextArea getMessage() {
        return message;
    }
    
    
    // Getter for UI elements
    public javax.swing.JButton getSendButton() {
        return send;
    }
    
    public javax.swing.JButton getVehicleButton() {
        return vehicles;
    }
    
    public javax.swing.JButton getRouteButton() {
        return routes;
    }
    
    public javax.swing.JButton getUserButton() {
        return users;
    }
    
    public javax.swing.JButton getNotificationButton() {
        return notifications;
    }
}