/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.RouteController;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class RouteManagement extends javax.swing.JFrame {
    private int editingRouteId = -1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RouteManagement.class.getName());

    /**
     * Creates new form VehicleManagement
     */
    public RouteManagement() {
        initComponents();
        RouteTable.getColumnModel().getColumn(0).setMinWidth(0);
        RouteTable.getColumnModel().getColumn(0).setMaxWidth(0);
        RouteTable.getColumnModel().getColumn(0).setWidth(0);

        setSize(1280, 740);
        RouteController controller = new RouteController();
        controller.loadRoutes(this);
        
        RouteTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = RouteTable.rowAtPoint(evt.getPoint());
                int col = RouteTable.columnAtPoint(evt.getPoint());
                
                if (col == 6) {
                    String[] options = {"Edit", "Delete"};
                    int choice = JOptionPane.showOptionDialog(
                            null,
                            "Choose an action",
                            "Action",
                            JOptionPane.DEFAULT_OPTION,
                            JOptionPane.INFORMATION_MESSAGE,
                            null,
                            options,
                            options[0]
                    );
                    
                    if (choice == 0) {
                        editRoute(row);
                    } else if (choice == 1) {
                        deleteRoute(row);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        Bato = new javax.swing.JLabel();
        AdminDashboard = new javax.swing.JLabel();
        intro = new javax.swing.JLabel();
        vehicles = new javax.swing.JButton();
        routes = new javax.swing.JButton();
        trips = new javax.swing.JButton();
        users = new javax.swing.JButton();
        notifications = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        RouteManagement = new javax.swing.JLabel();
        AddRoute = new javax.swing.JButton();
        form = new javax.swing.JPanel();
        AddNewRoute = new javax.swing.JLabel();
        RouteName = new javax.swing.JLabel();
        RouteNameText = new javax.swing.JTextField();
        Destination = new javax.swing.JLabel();
        DestinationText = new javax.swing.JTextField();
        Origin = new javax.swing.JLabel();
        Driver = new javax.swing.JLabel();
        SubmitRoute = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        FareText = new javax.swing.JTextField();
        OriginText = new javax.swing.JTextField();
        Duration = new javax.swing.JLabel();
        DurationText = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        RouteTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        header.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        Bato.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        Bato.setText("Bato+");
        Bato.setMaximumSize(new java.awt.Dimension(117, 47));
        Bato.setMinimumSize(new java.awt.Dimension(117, 47));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(Bato, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1065, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addComponent(Bato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(header);
        header.setBounds(0, 0, 1280, 95);

        AdminDashboard.setBackground(new java.awt.Color(255, 255, 255));
        AdminDashboard.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        AdminDashboard.setText("Admin Dashboard");
        AdminDashboard.setMaximumSize(new java.awt.Dimension(356, 47));
        AdminDashboard.setMinimumSize(new java.awt.Dimension(356, 47));
        getContentPane().add(AdminDashboard);
        AdminDashboard.setBounds(40, 120, 250, 50);

        intro.setBackground(new java.awt.Color(153, 153, 153));
        intro.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        intro.setForeground(new java.awt.Color(153, 153, 153));
        intro.setText("Manage vehicles, routes, trips, and users");
        getContentPane().add(intro);
        intro.setBounds(40, 160, 290, 20);

        vehicles.setBackground(new java.awt.Color(244, 244, 244));
        vehicles.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        vehicles.setForeground(new java.awt.Color(102, 102, 102));
        vehicles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vehicleIcon.png"))); // NOI18N
        vehicles.setText("Vehicles");
        vehicles.setBorder(null);
        vehicles.setBorderPainted(false);
        vehicles.setContentAreaFilled(false);
        vehicles.addActionListener(this::vehiclesActionPerformed);
        getContentPane().add(vehicles);
        vehicles.setBounds(30, 193, 110, 40);

        routes.setBackground(new java.awt.Color(244, 244, 244));
        routes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        routes.setForeground(new java.awt.Color(0, 0, 204));
        routes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/selectedRoute.png"))); // NOI18N
        routes.setText("Routes");
        routes.setBorder(null);
        routes.setBorderPainted(false);
        routes.setContentAreaFilled(false);
        routes.addActionListener(this::routesActionPerformed);
        getContentPane().add(routes);
        routes.setBounds(140, 193, 110, 40);

        trips.setBackground(new java.awt.Color(244, 244, 244));
        trips.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        trips.setForeground(new java.awt.Color(102, 102, 102));
        trips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tripIcon.png"))); // NOI18N
        trips.setText("Trips");
        trips.setBorder(null);
        trips.setBorderPainted(false);
        trips.setContentAreaFilled(false);
        getContentPane().add(trips);
        trips.setBounds(250, 193, 110, 40);

        users.setBackground(new java.awt.Color(244, 244, 244));
        users.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        users.setForeground(new java.awt.Color(102, 102, 102));
        users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userIcon.png"))); // NOI18N
        users.setText("Users");
        users.setBorder(null);
        users.setBorderPainted(false);
        users.setContentAreaFilled(false);
        getContentPane().add(users);
        users.setBounds(360, 193, 110, 40);

        notifications.setBackground(new java.awt.Color(244, 244, 244));
        notifications.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        notifications.setForeground(new java.awt.Color(102, 102, 102));
        notifications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/notifIcon.png"))); // NOI18N
        notifications.setText("Notifications");
        notifications.setBorder(null);
        notifications.setBorderPainted(false);
        notifications.setContentAreaFilled(false);
        getContentPane().add(notifications);
        notifications.setBounds(470, 193, 110, 40);

        separator.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(separator);
        separator.setBounds(30, 230, 1205, 20);

        RouteManagement.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        RouteManagement.setText("Route Management");
        getContentPane().add(RouteManagement);
        RouteManagement.setBounds(50, 240, 240, 54);

        AddRoute.setBackground(new java.awt.Color(0, 0, 204));
        AddRoute.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        AddRoute.setForeground(new java.awt.Color(255, 255, 255));
        AddRoute.setText("+ Add Route");
        AddRoute.addActionListener(this::AddRouteActionPerformed);
        getContentPane().add(AddRoute);
        AddRoute.setBounds(1070, 240, 150, 40);

        form.setBackground(new java.awt.Color(255, 255, 255));
        form.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        form.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        AddNewRoute.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddNewRoute.setText("Add New Route");

        RouteName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        RouteName.setText("Route Name");

        RouteNameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RouteNameText.setToolTipText("");
        RouteNameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RouteNameText.addActionListener(this::RouteNameTextActionPerformed);

        Destination.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Destination.setText("Destination");

        DestinationText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DestinationText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Origin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Origin.setText("Origin");

        Driver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Driver.setText("Fare");

        SubmitRoute.setBackground(new java.awt.Color(0, 0, 204));
        SubmitRoute.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        SubmitRoute.setForeground(new java.awt.Color(255, 255, 255));
        SubmitRoute.setText("Add Route");
        SubmitRoute.addActionListener(this::SubmitRouteActionPerformed);

        cancel.setBackground(new java.awt.Color(153, 153, 153));
        cancel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(this::cancelActionPerformed);

        FareText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FareText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FareText.addActionListener(this::FareTextActionPerformed);

        OriginText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OriginText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        OriginText.addActionListener(this::OriginTextActionPerformed);

        Duration.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Duration.setText("Duration (in minutes)");

        DurationText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DurationText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DurationText.addActionListener(this::DurationTextActionPerformed);

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Duration)
                    .addGroup(formLayout.createSequentialGroup()
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RouteName)
                            .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(DestinationText)
                                .addComponent(AddNewRoute, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Destination, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RouteNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formLayout.createSequentialGroup()
                                    .addComponent(SubmitRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(DurationText, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(44, 44, 44)
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Origin)
                            .addComponent(Driver)
                            .addComponent(FareText, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OriginText, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(AddNewRoute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RouteName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RouteNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OriginText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Driver)
                            .addComponent(Destination)))
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Origin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FareText, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(DestinationText))
                .addGap(12, 12, 12)
                .addComponent(Duration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(DurationText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(form);
        form.setBounds(60, 310, 1150, 310);

        scroll.setPreferredSize(new java.awt.Dimension(450, 60));

        RouteTable.setForeground(new java.awt.Color(51, 51, 51));
        RouteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Origin", "Destination", "Fare", "Duration", "Actions"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        RouteTable.setPreferredSize(new java.awt.Dimension(450, 500));
        scroll.setViewportView(RouteTable);

        getContentPane().add(scroll);
        scroll.setBounds(60, 640, 1150, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RouteNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RouteNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RouteNameTextActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        form.setVisible(false);
        scroll.setBounds(60, 310, 1150, 350);
    }//GEN-LAST:event_cancelActionPerformed

    private void routesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routesActionPerformed

    private void FareTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FareTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FareTextActionPerformed

    private void OriginTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OriginTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OriginTextActionPerformed

    private void DurationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DurationTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DurationTextActionPerformed

    private void SubmitRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitRouteActionPerformed
        // TODO add your handling code here:
        String routename = RouteNameText.getText().trim();
        String origin = OriginText.getText().trim();
        String destination = DestinationText.getText().trim();
        String durationStr = DurationText.getText().trim();
        String fareStr = FareText.getText().trim();
        
        if (routename.isEmpty() || origin.isEmpty() || destination.isEmpty() || durationStr.isEmpty() || fareStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all the fields!");
            return;
        }
        
        int duration = Integer.parseInt(durationStr);
        double fare = Double.parseDouble(fareStr);
        
        RouteController controller = new RouteController();
        controller.addRoute(routename, origin, destination, duration, fare);
        
        loadRouteTable();
        
        RouteNameText.setText("");
        OriginText.setText("");
        DestinationText.setText("");
        DurationText.setText("");
        FareText.setText("");
        
        form.setVisible(false);
        scroll.setBounds(60, 310, 1150, 70);
        
        JOptionPane.showMessageDialog(this, "Route added successfully!");   
    }//GEN-LAST:event_SubmitRouteActionPerformed

    private void vehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiclesActionPerformed
        // TODO add your handling code here:
        RouteController controller = new RouteController();
        controller.closeRouteManagement(this);
        controller.openVehicleManagement();
    }//GEN-LAST:event_vehiclesActionPerformed

    private void AddRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRouteActionPerformed
        // TODO add your handling code here:
        form.setVisible(true);
        scroll.setBounds(60, 640, 1150, 70);
    }//GEN-LAST:event_AddRouteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RouteManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddNewRoute;
    private javax.swing.JButton AddRoute;
    private javax.swing.JLabel AdminDashboard;
    private javax.swing.JLabel Bato;
    private javax.swing.JLabel Destination;
    private javax.swing.JTextField DestinationText;
    private javax.swing.JLabel Driver;
    private javax.swing.JLabel Duration;
    private javax.swing.JTextField DurationText;
    private javax.swing.JTextField FareText;
    private javax.swing.JLabel Origin;
    private javax.swing.JTextField OriginText;
    private javax.swing.JLabel RouteManagement;
    private javax.swing.JLabel RouteName;
    private javax.swing.JTextField RouteNameText;
    private javax.swing.JTable RouteTable;
    private javax.swing.JButton SubmitRoute;
    private javax.swing.JButton cancel;
    private javax.swing.JPanel form;
    private javax.swing.JPanel header;
    private javax.swing.JLabel intro;
    private javax.swing.JLabel logo;
    private javax.swing.JButton notifications;
    private javax.swing.JButton routes;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JSeparator separator;
    private javax.swing.JButton trips;
    private javax.swing.JButton users;
    private javax.swing.JButton vehicles;
    // End of variables declaration//GEN-END:variables
public javax.swing.JTextField getRouteName() {
    return RouteNameText;
}

public javax.swing.JTextField getOriginName() {
    return OriginText;
}

public javax.swing.JTextField getDestinationName() {
    return DestinationText;
}

public javax.swing.JTextField getFare() {
    return FareText;
}

public javax.swing.JTextField getDuration() {
    return DurationText;
}

public javax.swing.JTable getRouteTable() {
    return RouteTable;
}

private void loadRouteTable() {
    RouteController controller = new RouteController();
    controller.loadRoutes(this);
}

private void editRoute(int row) {

    int id = (int) RouteTable.getValueAt(row, 0);
    String name = (String) RouteTable.getValueAt(row, 1);
    String origin = (String) RouteTable.getValueAt(row, 2);
    String destination = (String) RouteTable.getValueAt(row, 3);
    double fare = (double) RouteTable.getValueAt(row, 4);
    int duration = (int) RouteTable.getValueAt(row, 5);

    RouteNameText.setText(name);
    OriginText.setText(origin);
    DestinationText.setText(destination);
    FareText.setText(String.valueOf(fare));
    DurationText.setText(String.valueOf(duration));

    editingRouteId = id;

    SubmitRoute.setText("Update Route");

    form.setVisible(true);
    scroll.setBounds(60, 640, 1150, 70);
}

private void deleteRoute(int row) {
    int id = (int) RouteTable.getValueAt(row, 0);

    int confirm = JOptionPane.showConfirmDialog(
            null,
            "Are you sure you want to delete this route?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        RouteController controller = new RouteController();
        controller.deleteRoute(id);
        loadRouteTable();
    }
}
}
