/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Asus
 */
public class SearchTrips extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchTrips.class.getName());

    /**
     * Creates new form PassengerDashboard_SearchTrips
     */
    public SearchTrips() {
        initComponents();
        this.setLocationRelativeTo(null); // centers the window
        this.setVisible(true); // makes sure it shows
        this.toFront();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        Bato = new javax.swing.JLabel();
        profile = new javax.swing.JButton();
        PassengerDashboard = new javax.swing.JLabel();
        intro = new javax.swing.JLabel();
        trip = new javax.swing.JButton();
        booking = new javax.swing.JButton();
        FindYourRide = new javax.swing.JLabel();
        navigation = new javax.swing.JPanel();
        Vechicle = new javax.swing.JLabel();
        all = new javax.swing.JButton();
        bus = new javax.swing.JButton();
        micro = new javax.swing.JButton();
        tempo = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        destination = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        noData = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        header.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        Bato.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        Bato.setText("Bato+");

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile.png"))); // NOI18N
        profile.setBorder(null);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1012, Short.MAX_VALUE)
                .addComponent(profile)
                .addGap(16, 16, 16))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile)
                    .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Bato)
                        .addComponent(logo)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(header);
        header.setBounds(0, 0, 1280, 100);

        PassengerDashboard.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        PassengerDashboard.setText("Passenger Dashboard");
        getContentPane().add(PassengerDashboard);
        PassengerDashboard.setBounds(20, 130, 320, 50);

        intro.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        intro.setForeground(new java.awt.Color(153, 153, 153));
        intro.setText("Manage Trips");
        getContentPane().add(intro);
        intro.setBounds(20, 180, 110, 21);

        trip.setBackground(new java.awt.Color(0, 51, 255));
        trip.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        trip.setForeground(new java.awt.Color(255, 255, 255));
        trip.setText("Search Trips");
        trip.addActionListener(this::tripActionPerformed);
        getContentPane().add(trip);
        trip.setBounds(20, 230, 140, 36);

        booking.setBackground(new java.awt.Color(204, 204, 204));
        booking.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        booking.setForeground(new java.awt.Color(102, 102, 102));
        booking.setText("My Bookings");
        getContentPane().add(booking);
        booking.setBounds(180, 230, 150, 30);

        FindYourRide.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        FindYourRide.setText("Find Your Ride");
        getContentPane().add(FindYourRide);
        FindYourRide.setBounds(20, 310, 170, 32);

        navigation.setBackground(new java.awt.Color(255, 255, 255));

        Vechicle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Vechicle.setText("Vehicle Type");

        all.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        all.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/All.png"))); // NOI18N
        all.setText("All");
        all.setBorder(null);
        all.setBorderPainted(false);
        all.setContentAreaFilled(false);
        all.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        all.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bus3 (2).png"))); // NOI18N
        bus.setText("Bus");
        bus.setBorder(null);
        bus.setBorderPainted(false);
        bus.setContentAreaFilled(false);
        bus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        micro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        micro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Shuttlebus.png"))); // NOI18N
        micro.setText("Micro");
        micro.setBorder(null);
        micro.setBorderPainted(false);
        micro.setContentAreaFilled(false);
        micro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        micro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tempo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tempo (2).png"))); // NOI18N
        tempo.setText("Tempo");
        tempo.setBorder(null);
        tempo.setBorderPainted(false);
        tempo.setContentAreaFilled(false);
        tempo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tempo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Title.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Title.setText("Destination");

        destination.setBackground(new java.awt.Color(255, 255, 255));
        destination.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        destination.setForeground(new java.awt.Color(102, 102, 102));
        destination.setText("Enter Destination");
        destination.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                destinationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                destinationFocusLost(evt);
            }
        });
        destination.addActionListener(this::destinationActionPerformed);

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Location.png"))); // NOI18N
        search.addActionListener(this::searchActionPerformed);

        javax.swing.GroupLayout navigationLayout = new javax.swing.GroupLayout(navigation);
        navigation.setLayout(navigationLayout);
        navigationLayout.setHorizontalGroup(
            navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Vechicle, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(navigationLayout.createSequentialGroup()
                        .addComponent(all)
                        .addGap(29, 29, 29)
                        .addComponent(bus)
                        .addGap(28, 28, 28)
                        .addComponent(micro)
                        .addGap(34, 34, 34)
                        .addComponent(tempo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addGroup(navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(navigationLayout.createSequentialGroup()
                        .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search)))
                .addGap(127, 127, 127))
        );
        navigationLayout.setVerticalGroup(
            navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vechicle)
                    .addComponent(Title))
                .addGap(18, 18, 18)
                .addGroup(navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(all)
                    .addComponent(bus)
                    .addComponent(tempo)
                    .addComponent(micro)
                    .addGroup(navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(destination, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(search, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(navigation);
        navigation.setBounds(20, 370, 1250, 160);

        noData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        noData.setText("No trips available matching your criteria");
        noData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        noData.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(noData);
        noData.setBounds(520, 600, 250, 77);

        resultTable.setForeground(new java.awt.Color(51, 51, 51));
        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Vehicle Number", "Vehicle Type", "Origin", "Destination", "Departure", "Arrival", "Fare", "Available Seats", "Book"
            }
        ));
        scroll.setViewportView(resultTable);
        if (resultTable.getColumnModel().getColumnCount() > 0) {
            resultTable.getColumnModel().getColumn(0).setMinWidth(0);
            resultTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            resultTable.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(scroll);
        scroll.setBounds(20, 550, 1250, 160);

        setBounds(1280, 740, 1294, 748);
    }// </editor-fold>//GEN-END:initComponents

    private void tripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tripActionPerformed

    private void destinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void destinationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_destinationFocusGained
        // Removes placeholder
        if (destination.getText().equals("Enter Destination")) {
            destination.setText("");
        }
    }//GEN-LAST:event_destinationFocusGained

    private void destinationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_destinationFocusLost
        // Adds placeholder if empty
        if (destination.getText().equals("")) {
            destination.setText("Enter Destination");
        }
    }//GEN-LAST:event_destinationFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SearchTrips().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bato;
    private javax.swing.JLabel FindYourRide;
    private javax.swing.JLabel PassengerDashboard;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Vechicle;
    private javax.swing.JButton all;
    private javax.swing.JButton booking;
    private javax.swing.JButton bus;
    private javax.swing.JTextField destination;
    private javax.swing.JPanel header;
    private javax.swing.JLabel intro;
    private javax.swing.JLabel logo;
    private javax.swing.JButton micro;
    private javax.swing.JPanel navigation;
    private javax.swing.JLabel noData;
    private javax.swing.JButton profile;
    private javax.swing.JTable resultTable;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JButton search;
    private javax.swing.JButton tempo;
    private javax.swing.JButton trip;
    // End of variables declaration//GEN-END:variables

    
    // What happens when user clicks button
    public void SearchListener(ActionListener listener) {
        search.addActionListener(listener);
    }
    
    public void AllListener(ActionListener listener) {
        all.addActionListener(listener);
    }
    
    public void BusListener(ActionListener listener) {
        bus.addActionListener(listener);
    }
    
    public void MicroListener(ActionListener listener) {
        micro.addActionListener(listener);
    }
    
    public void TempoListener(ActionListener listener) {
        tempo.addActionListener(listener);
    }
    
    public void BookingListener(ActionListener listener) {
        booking.addActionListener(listener);
    }
    
    public void ProfileListener(ActionListener listener) {
        profile.addActionListener(listener);
    }
    
    
    // Read / Manipulate value entered by user
    public javax.swing.JTextField getDestination() {
        return destination;
    }
    
    
    // Getter for UI elements
    public javax.swing.JButton getSearchButton() {
        return search;
    }
    
    public javax.swing.JButton getAllButton() {
        return all;
    }
    
    public javax.swing.JButton getBusButton() {
        return bus;
    }
    
    public javax.swing.JButton getMicroButton() {
        return micro;
    }
    
    public javax.swing.JButton getTempoButton() {
        return tempo;
    }
    
    public javax.swing.JButton getBookingButton() {
        return booking;
    }
    
    public javax.swing.JButton getProfileButton() {
        return profile;
    }
    
    public JScrollPane getScrollPane() {
        return scroll;
    }
    
    public JTable getResultTable() {
        return resultTable;
    }
    
    public JLabel getNoData() {
        return noData;
    }
}