/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author user
 */
public class Signup extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Signup.class.getName());

    /**
     * Creates new form Login
     */
    public Signup() {
        initComponents();
        setSize(1000,564);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        SignUp = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        Phone = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        Role = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        signUp = new javax.swing.JButton();
        Account = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        formBackground = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SignupIcon.png"))); // NOI18N
        getContentPane().add(icon);
        icon.setBounds(420, 60, 40, 40);

        SignUp.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        SignUp.setForeground(new java.awt.Color(102, 102, 102));
        SignUp.setText("Sign Up");
        getContentPane().add(SignUp);
        SignUp.setBounds(470, 60, 96, 40);

        Name.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Name.setForeground(new java.awt.Color(95, 95, 95));
        Name.setText("Full Name");
        getContentPane().add(Name);
        Name.setBounds(390, 120, 60, 16);

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setForeground(new java.awt.Color(102, 102, 102));
        name.setText("Enter Your Name");
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 95, 95)));
        name.addActionListener(this::nameActionPerformed);
        getContentPane().add(name);
        name.setBounds(390, 140, 220, 18);

        Email.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Email.setForeground(new java.awt.Color(95, 95, 95));
        Email.setText("Email");
        getContentPane().add(Email);
        Email.setBounds(390, 170, 29, 16);

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setText("Enter Your Email");
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 95, 95)));
        email.addActionListener(this::emailActionPerformed);
        getContentPane().add(email);
        email.setBounds(390, 190, 220, 18);

        Phone.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Phone.setForeground(new java.awt.Color(95, 95, 95));
        Phone.setText("Phone");
        getContentPane().add(Phone);
        Phone.setBounds(390, 220, 40, 16);

        phone.setBackground(new java.awt.Color(255, 255, 255));
        phone.setForeground(new java.awt.Color(102, 102, 102));
        phone.setText("Enter Your Phone");
        phone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 95, 95)));
        phone.addActionListener(this::phoneActionPerformed);
        getContentPane().add(phone);
        phone.setBounds(390, 240, 220, 18);

        Address.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Address.setForeground(new java.awt.Color(95, 95, 95));
        Address.setText("Address");
        getContentPane().add(Address);
        Address.setBounds(390, 270, 50, 16);

        address.setBackground(new java.awt.Color(255, 255, 255));
        address.setForeground(new java.awt.Color(102, 102, 102));
        address.setText("Enter Your Address");
        address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 95, 95)));
        address.addActionListener(this::addressActionPerformed);
        getContentPane().add(address);
        address.setBounds(390, 290, 220, 18);

        Password.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Password.setForeground(new java.awt.Color(95, 95, 95));
        Password.setText("Password");
        getContentPane().add(Password);
        Password.setBounds(390, 320, 60, 16);

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setForeground(new java.awt.Color(102, 102, 102));
        password.setText("Enter Your Password");
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 95, 95)));
        password.addActionListener(this::passwordActionPerformed);
        getContentPane().add(password);
        password.setBounds(390, 350, 220, 18);

        Role.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Role.setForeground(new java.awt.Color(95, 95, 95));
        Role.setText("Role");
        getContentPane().add(Role);
        Role.setBounds(390, 380, 30, 16);

        role.setBackground(new java.awt.Color(255, 255, 255));
        role.setForeground(new java.awt.Color(51, 51, 51));
        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your Role", "Passenger", "Driver" }));
        role.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        role.addActionListener(this::roleActionPerformed);
        getContentPane().add(role);
        role.setBounds(390, 400, 220, 22);

        signUp.setBackground(new java.awt.Color(0, 0, 204));
        signUp.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        signUp.setText("SIGN IN");
        signUp.addActionListener(this::signUpActionPerformed);
        getContentPane().add(signUp);
        signUp.setBounds(450, 440, 96, 29);

        Account.setForeground(new java.awt.Color(95, 95, 95));
        Account.setText("Already have an account?");
        getContentPane().add(Account);
        Account.setBounds(410, 470, 140, 16);

        login.setBackground(new java.awt.Color(244, 244, 244));
        login.setForeground(new java.awt.Color(0, 0, 204));
        login.setText("Sign in");
        login.setBorder(null);
        login.setBorderPainted(false);
        login.setContentAreaFilled(false);
        login.addActionListener(this::loginActionPerformed);
        getContentPane().add(login);
        login.setBounds(550, 470, 40, 16);

        formBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SignupBackground.png"))); // NOI18N
        formBackground.setMaximumSize(new java.awt.Dimension(259, 259));
        formBackground.setMinimumSize(new java.awt.Dimension(259, 259));
        formBackground.setPreferredSize(new java.awt.Dimension(259, 259));
        getContentPane().add(formBackground);
        formBackground.setBounds(370, 40, 260, 460);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SignBackground.jpg"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(1000, 564));
        background.setMinimumSize(new java.awt.Dimension(1000, 564));
        background.setPreferredSize(new java.awt.Dimension(1000, 564));
        getContentPane().add(background);
        background.setBounds(0, 0, 1000, 564);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpActionPerformed

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Signup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Account;
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel Role;
    private javax.swing.JLabel SignUp;
    private javax.swing.JTextField address;
    private javax.swing.JLabel background;
    private javax.swing.JTextField email;
    private javax.swing.JLabel formBackground;
    private javax.swing.JLabel icon;
    private javax.swing.JButton login;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JButton signUp;
    // End of variables declaration//GEN-END:variables
}