/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author hp
 */
public class TripManagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TripManagement.class.getName());

    /**
     * Creates new form VehicleManagement
     */
    public TripManagement() {
        initComponents();
        setSize(1280, 740);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        Bato = new javax.swing.JLabel();
        profile = new javax.swing.JButton();
        AdminDashboard = new javax.swing.JLabel();
        intro = new javax.swing.JLabel();
        vehicles = new javax.swing.JButton();
        routes = new javax.swing.JButton();
        trips = new javax.swing.JButton();
        users = new javax.swing.JButton();
        notifications = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        TripManagement = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        form = new javax.swing.JPanel();
        ScheduleTrip = new javax.swing.JLabel();
        Vehicle = new javax.swing.JLabel();
        vehicle = new javax.swing.JComboBox<>();
        DepartureTime = new javax.swing.JLabel();
        departure = new javax.swing.JTextField();
        Route = new javax.swing.JLabel();
        route = new javax.swing.JComboBox<>();
        ArrivalTime = new javax.swing.JLabel();
        arrival = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        noData = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        tripTable = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        header.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        Bato.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        Bato.setText("Bato+");
        Bato.setMaximumSize(new java.awt.Dimension(117, 47));
        Bato.setMinimumSize(new java.awt.Dimension(117, 47));

        profile.setBackground(new java.awt.Color(244, 244, 244));
        profile.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        profile.setForeground(new java.awt.Color(102, 102, 102));
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile.png"))); // NOI18N
        profile.setBorder(null);
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(Bato, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 979, Short.MAX_VALUE)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo)
                            .addComponent(Bato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))))
        );

        getContentPane().add(header);
        header.setBounds(0, 0, 1280, 95);

        AdminDashboard.setBackground(new java.awt.Color(255, 255, 255));
        AdminDashboard.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        AdminDashboard.setText("Admin Dashboard");
        AdminDashboard.setMaximumSize(new java.awt.Dimension(356, 47));
        AdminDashboard.setMinimumSize(new java.awt.Dimension(356, 47));
        getContentPane().add(AdminDashboard);
        AdminDashboard.setBounds(40, 120, 250, 50);

        intro.setBackground(new java.awt.Color(153, 153, 153));
        intro.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        intro.setForeground(new java.awt.Color(153, 153, 153));
        intro.setText("Manage vehicles, routes, trips, and users");
        getContentPane().add(intro);
        intro.setBounds(40, 160, 290, 20);

        vehicles.setBackground(new java.awt.Color(244, 244, 244));
        vehicles.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        vehicles.setForeground(new java.awt.Color(102, 102, 102));
        vehicles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vehicleIcon.png"))); // NOI18N
        vehicles.setText("Vehicles");
        vehicles.setBorder(null);
        vehicles.setBorderPainted(false);
        vehicles.setContentAreaFilled(false);
        getContentPane().add(vehicles);
        vehicles.setBounds(30, 193, 110, 40);

        routes.setBackground(new java.awt.Color(244, 244, 244));
        routes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        routes.setForeground(new java.awt.Color(102, 102, 102));
        routes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/routeIcon.png"))); // NOI18N
        routes.setText("Routes");
        routes.setBorder(null);
        routes.setBorderPainted(false);
        routes.setContentAreaFilled(false);
        routes.addActionListener(this::routesActionPerformed);
        getContentPane().add(routes);
        routes.setBounds(140, 193, 110, 40);

        trips.setBackground(new java.awt.Color(244, 244, 244));
        trips.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        trips.setForeground(new java.awt.Color(0, 0, 204));
        trips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/selectedTrip.png"))); // NOI18N
        trips.setText("Trips");
        trips.setBorder(null);
        trips.setBorderPainted(false);
        trips.setContentAreaFilled(false);
        getContentPane().add(trips);
        trips.setBounds(250, 193, 110, 40);

        users.setBackground(new java.awt.Color(244, 244, 244));
        users.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        users.setForeground(new java.awt.Color(102, 102, 102));
        users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userIcon.png"))); // NOI18N
        users.setText("Users");
        users.setBorder(null);
        users.setBorderPainted(false);
        users.setContentAreaFilled(false);
        getContentPane().add(users);
        users.setBounds(360, 193, 110, 40);

        notifications.setBackground(new java.awt.Color(244, 244, 244));
        notifications.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        notifications.setForeground(new java.awt.Color(102, 102, 102));
        notifications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/notifIcon.png"))); // NOI18N
        notifications.setText("Notifications");
        notifications.setBorder(null);
        notifications.setBorderPainted(false);
        notifications.setContentAreaFilled(false);
        getContentPane().add(notifications);
        notifications.setBounds(470, 193, 110, 40);

        separator.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(separator);
        separator.setBounds(30, 230, 1205, 20);

        TripManagement.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        TripManagement.setText("Trip Management");
        getContentPane().add(TripManagement);
        TripManagement.setBounds(50, 240, 240, 54);

        add.setBackground(new java.awt.Color(0, 0, 204));
        add.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("+ Schedule Trips");
        add.addActionListener(this::addActionPerformed);
        getContentPane().add(add);
        add.setBounds(1070, 240, 150, 40);

        form.setBackground(new java.awt.Color(255, 255, 255));
        form.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        form.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ScheduleTrip.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ScheduleTrip.setText("Schedule New Trip");

        Vehicle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Vehicle.setText("Vehicle");

        vehicle.setBackground(new java.awt.Color(255, 255, 255));
        vehicle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        vehicle.setForeground(new java.awt.Color(51, 51, 51));
        vehicle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the Vehicle", " " }));
        vehicle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        DepartureTime.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        DepartureTime.setText("Departure Time");

        departure.setBackground(new java.awt.Color(255, 255, 255));
        departure.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        departure.setText("yyyy-mm-dd hh:mm:ss");
        departure.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        departure.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                departureFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                departureFocusLost(evt);
            }
        });

        Route.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Route.setText("Route");

        route.setBackground(new java.awt.Color(255, 255, 255));
        route.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        route.setForeground(new java.awt.Color(51, 51, 51));
        route.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the Route", " " }));
        route.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        route.addActionListener(this::routeActionPerformed);

        ArrivalTime.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ArrivalTime.setText("Arrival Time");

        arrival.setBackground(new java.awt.Color(255, 255, 255));
        arrival.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        arrival.setText("yyyy-mm-dd hh:mm:ss");
        arrival.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        arrival.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                arrivalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                arrivalFocusLost(evt);
            }
        });
        arrival.addActionListener(this::arrivalActionPerformed);

        confirm.setBackground(new java.awt.Color(0, 0, 204));
        confirm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("Schedule Trip");

        cancel.setBackground(new java.awt.Color(153, 153, 153));
        cancel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(this::cancelActionPerformed);

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Vehicle)
                    .addComponent(ScheduleTrip)
                    .addComponent(DepartureTime)
                    .addGroup(formLayout.createSequentialGroup()
                        .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departure, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Route)
                            .addComponent(ArrivalTime)
                            .addComponent(route, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(arrival)))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(ScheduleTrip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Vehicle)
                        .addGap(6, 6, 6)
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(route, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Route)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ArrivalTime)
                    .addComponent(DepartureTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(form);
        form.setBounds(60, 310, 1150, 250);

        noData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noData.setText("No Records");
        getContentPane().add(noData);
        noData.setBounds(600, 660, 80, 20);

        tripTable.setForeground(new java.awt.Color(51, 51, 51));
        tripTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Vehicle", "Routes", "Departure", "Arrival", "Status", "Actions"
            }
        ));

        scroll.setViewportView(tripTable);
        if (tripTable.getColumnModel().getColumnCount() > 0) {
            tripTable.getColumnModel().getColumn(0).setMinWidth(0);
            tripTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            tripTable.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(scroll);
        scroll.setBounds(60, 610, 1150, 100);

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DashboardBackground.png"))); // NOI18N
        background.setFocusable(false);
        background.setMaximumSize(new java.awt.Dimension(1024, 640));
        background.setMinimumSize(new java.awt.Dimension(1024, 640));
        background.setPreferredSize(new java.awt.Dimension(1480, 1024));
        getContentPane().add(background);
        background.setBounds(0, 0, 1440, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void routesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routesActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void routeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routeActionPerformed

    private void departureFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_departureFocusGained
        // Removes placeholder
        if (departure.getText().equals("yyyy-mm-dd hh:mm:ss")) {
            departure.setText("");
        }
    }//GEN-LAST:event_departureFocusGained

    private void departureFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_departureFocusLost
        // Adds placeholder if empty
        if (departure.getText().equals("")) {
            departure.setText("yyyy-mm-dd hh:mm:ss");
        }
    }//GEN-LAST:event_departureFocusLost

    private void arrivalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_arrivalFocusGained
        // Removes placeholder
        if (arrival.getText().equals("yyyy-mm-dd hh:mm:ss")) {
            arrival.setText("");
        }
    }//GEN-LAST:event_arrivalFocusGained

    private void arrivalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_arrivalFocusLost
        // Adds placeholder if empty
        if (arrival.getText().equals("")) {
            arrival.setText("yyyy-mm-dd hh:mm:ss");
        }
    }//GEN-LAST:event_arrivalFocusLost

    private void arrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrivalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TripManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDashboard;
    private javax.swing.JLabel ArrivalTime;
    private javax.swing.JLabel Bato;
    private javax.swing.JLabel DepartureTime;
    private javax.swing.JLabel Route;
    private javax.swing.JLabel ScheduleTrip;
    private javax.swing.JLabel TripManagement;
    private javax.swing.JLabel Vehicle;
    private javax.swing.JButton add;
    private javax.swing.JTextField arrival;
    private javax.swing.JLabel background;
    private javax.swing.JButton cancel;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField departure;
    private javax.swing.JPanel form;
    private javax.swing.JPanel header;
    private javax.swing.JLabel intro;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel noData;
    private javax.swing.JButton notifications;
    private javax.swing.JButton profile;
    private javax.swing.JComboBox<String> route;
    private javax.swing.JButton routes;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JSeparator separator;
    private javax.swing.JTable tripTable;
    private javax.swing.JButton trips;
    private javax.swing.JButton users;
    private javax.swing.JComboBox<String> vehicle;
    private javax.swing.JButton vehicles;
    // End of variables declaration//GEN-END:variables

    
    // What happens when user clicks button
    public void TripFormListener(ActionListener listener) {
        add.addActionListener(listener);
    }
    
    public void AddTripListener(ActionListener listener) {
        confirm.addActionListener(listener);
    }
    
    public void CancelTripListener(ActionListener listener) {
        cancel.addActionListener(listener);
    }
    
    public void VehicleManagementListener(ActionListener listener) {
        vehicles.addActionListener(listener);
    }
    
    public void RouteManagementListener(ActionListener listener) {
        routes.addActionListener(listener);
    }
    
    public void UserManagementListener(ActionListener listener) {
        users.addActionListener(listener);
    }
    
    public void NotificationListener(ActionListener listener) {
        notifications.addActionListener(listener);
    }
    
    
    // Read / Manipulate value entered by user
    public javax.swing.JComboBox getVehicle() {
        return vehicle;
    }
    
    public javax.swing.JComboBox getRoute() {
        return route;
    }
    
    public javax.swing.JTextField getDeparture() {
        return departure;
    }
    
    public javax.swing.JTextField getArrival() {
        return arrival;
    }
    
    
    // Getter for UI elements
    public javax.swing.JButton getSubmitButton() {
        return confirm;
    }
    
    public javax.swing.JButton getVehicleButton() {
        return vehicles;
    }
    
    public javax.swing.JButton getRouteButton() {
        return routes;
    }
    
    public javax.swing.JButton getUserButton() {
        return users;
    }
    
    public javax.swing.JButton getNotificationButton() {
        return notifications;
    }
    
    public javax.swing.JPanel getFormPanel() {
        return form;
    }
    
    public JScrollPane getScrollPane() {
        return scroll;
    }
    
    public JTable getTripTable() {
        return tripTable;
    }
    
    public JLabel getNoData() {
        return noData;
    }
}