/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

<<<<<<< Updated upstream
=======
import Controller.TripController;
import Controller.VehicleController;
import DAO.userDAO;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

>>>>>>> Stashed changes
/**
 *
 * @author hp
 */
public class UserManagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserManagement.class.getName());

    /**
     * Creates new form VehicleManagement
     */
    public UserManagement() {
        initComponents();
        setSize(1280, 740);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        Bato = new javax.swing.JLabel();
        profile = new javax.swing.JButton();
        AdminDashboard = new javax.swing.JLabel();
        intro = new javax.swing.JLabel();
        vehicles = new javax.swing.JButton();
        routes = new javax.swing.JButton();
        trips = new javax.swing.JButton();
        users = new javax.swing.JButton();
        notifications = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        form = new javax.swing.JPanel();
        UsersManagement = new javax.swing.JLabel();
        all = new javax.swing.JButton();
        passsenger = new javax.swing.JButton();
        driver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        header.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        Bato.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        Bato.setForeground(new java.awt.Color(0, 0, 0));
        Bato.setText("Bato+");
        Bato.setMaximumSize(new java.awt.Dimension(117, 47));
        Bato.setMinimumSize(new java.awt.Dimension(117, 47));

        profile.setBackground(new java.awt.Color(244, 244, 244));
        profile.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        profile.setForeground(new java.awt.Color(102, 102, 102));
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile.png"))); // NOI18N
        profile.setBorder(null);
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(Bato, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 979, Short.MAX_VALUE)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo)
                            .addComponent(Bato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))))
        );

        getContentPane().add(header);
        header.setBounds(0, 0, 1280, 95);

        AdminDashboard.setBackground(new java.awt.Color(255, 255, 255));
        AdminDashboard.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        AdminDashboard.setForeground(new java.awt.Color(0, 0, 0));
        AdminDashboard.setText("Admin Dashboard");
        AdminDashboard.setMaximumSize(new java.awt.Dimension(356, 47));
        AdminDashboard.setMinimumSize(new java.awt.Dimension(356, 47));
        getContentPane().add(AdminDashboard);
        AdminDashboard.setBounds(40, 120, 250, 50);

        intro.setBackground(new java.awt.Color(153, 153, 153));
        intro.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        intro.setForeground(new java.awt.Color(153, 153, 153));
        intro.setText("Manage vehicles, routes, trips, and users");
        getContentPane().add(intro);
        intro.setBounds(40, 160, 290, 20);

        vehicles.setBackground(new java.awt.Color(244, 244, 244));
        vehicles.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        vehicles.setForeground(new java.awt.Color(102, 102, 102));
        vehicles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vehicleIcon.png"))); // NOI18N
        vehicles.setText("Vehicles");
        vehicles.setBorder(null);
        vehicles.setBorderPainted(false);
        vehicles.setContentAreaFilled(false);
        getContentPane().add(vehicles);
        vehicles.setBounds(30, 193, 110, 40);

        routes.setBackground(new java.awt.Color(244, 244, 244));
        routes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        routes.setForeground(new java.awt.Color(102, 102, 102));
        routes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/routeIcon.png"))); // NOI18N
        routes.setText("Routes");
        routes.setBorder(null);
        routes.setBorderPainted(false);
        routes.setContentAreaFilled(false);
        getContentPane().add(routes);
        routes.setBounds(140, 193, 110, 40);

        trips.setBackground(new java.awt.Color(244, 244, 244));
        trips.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        trips.setForeground(new java.awt.Color(102, 102, 102));
        trips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tripIcon.png"))); // NOI18N
        trips.setText("Trips");
        trips.setBorder(null);
        trips.setBorderPainted(false);
        trips.setContentAreaFilled(false);
        trips.addActionListener(this::tripsActionPerformed);
        getContentPane().add(trips);
        trips.setBounds(250, 193, 110, 40);

        users.setBackground(new java.awt.Color(244, 244, 244));
        users.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        users.setForeground(new java.awt.Color(0, 0, 204));
        users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/selectedUser.png"))); // NOI18N
        users.setText("Users");
        users.setBorder(null);
        users.setBorderPainted(false);
        users.setContentAreaFilled(false);
        getContentPane().add(users);
        users.setBounds(360, 193, 110, 40);

        notifications.setBackground(new java.awt.Color(244, 244, 244));
        notifications.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        notifications.setForeground(new java.awt.Color(102, 102, 102));
        notifications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/notifIcon.png"))); // NOI18N
        notifications.setText("Notifications");
        notifications.setBorder(null);
        notifications.setBorderPainted(false);
        notifications.setContentAreaFilled(false);
        getContentPane().add(notifications);
        notifications.setBounds(470, 193, 110, 40);

        separator.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(separator);
        separator.setBounds(30, 230, 1205, 20);

        form.setBackground(new java.awt.Color(255, 255, 255));
        form.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        form.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        UsersManagement.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        UsersManagement.setForeground(new java.awt.Color(0, 0, 0));
        UsersManagement.setText("Users Management");

        all.setBackground(new java.awt.Color(0, 0, 204));
        all.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        all.setForeground(new java.awt.Color(255, 255, 255));
        all.setText("All");
        all.addActionListener(this::allActionPerformed);

        passsenger.setBackground(new java.awt.Color(153, 153, 153));
        passsenger.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        passsenger.setForeground(new java.awt.Color(255, 255, 255));
        passsenger.setText("Passenger");
        passsenger.addActionListener(this::passsengerActionPerformed);

        driver.setBackground(new java.awt.Color(153, 153, 153));
        driver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        driver.setForeground(new java.awt.Color(255, 255, 255));
        driver.setText("Driver");
        driver.addActionListener(this::driverActionPerformed);

        usersTable.setBackground(new java.awt.Color(255, 255, 255));
        usersTable.setForeground(new java.awt.Color(51, 51, 51));
        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Phone", "Role", "Joined"
            }
        ));
        jScrollPane1.setViewportView(usersTable);

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(UsersManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formLayout.createSequentialGroup()
                                .addComponent(all, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(passsenger, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(driver)))))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(UsersManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(all, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passsenger, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        getContentPane().add(form);
        form.setBounds(60, 270, 1150, 300);

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DashboardBackground.png"))); // NOI18N
        background.setFocusable(false);
        background.setMaximumSize(new java.awt.Dimension(1024, 640));
        background.setMinimumSize(new java.awt.Dimension(1024, 640));
        background.setPreferredSize(new java.awt.Dimension(1480, 1024));
        getContentPane().add(background);
        background.setBounds(0, 0, 1440, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passsengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passsengerActionPerformed
        // TODO add your handling code here:
<<<<<<< Updated upstream
    }//GEN-LAST:event_passsengerActionPerformed
=======
        this.dispose();
        VehicleManagement vm = new VehicleManagement();
        VehicleController vc = new VehicleController(vm);
        vc.openVehicleManagement();
    }//GEN-LAST:event_vehiclesActionPerformed

    private void routesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        RouteManagement rm = new RouteManagement();
        rm.setVisible(true);
    }//GEN-LAST:event_routesActionPerformed

    private void usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usersActionPerformed
>>>>>>> Stashed changes

    private void allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allActionPerformed

    private void driverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverActionPerformed

    private void tripsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripsActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TripManagement tm = new TripManagement();
        TripController tc = new TripController(tm);
        tc.openTripManagement();
    }//GEN-LAST:event_tripsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDashboard;
    private javax.swing.JLabel Bato;
    private javax.swing.JLabel UsersManagement;
    private javax.swing.JButton all;
    private javax.swing.JLabel background;
    private javax.swing.JButton driver;
    private javax.swing.JPanel form;
    private javax.swing.JPanel header;
    private javax.swing.JLabel intro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton notifications;
    private javax.swing.JButton passsenger;
    private javax.swing.JButton profile;
    private javax.swing.JButton routes;
    private javax.swing.JSeparator separator;
    private javax.swing.JButton trips;
    private javax.swing.JButton users;
    private javax.swing.JTable usersTable;
    private javax.swing.JButton vehicles;
    // End of variables declaration//GEN-END:variables
}
