/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author hp
 */
public class VehicleManagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VehicleManagement.class.getName());

    /**
     * Creates new form VehicleManagement
     */
    public VehicleManagement() {
        initComponents();
        setSize(1280, 740);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        Bato = new javax.swing.JLabel();
        profile = new javax.swing.JButton();
        AdminDashboard = new javax.swing.JLabel();
        intro = new javax.swing.JLabel();
        vehicles = new javax.swing.JButton();
        routes = new javax.swing.JButton();
        trips = new javax.swing.JButton();
        users = new javax.swing.JButton();
        notifications = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        VehicleManagement = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        form = new javax.swing.JPanel();
        AddNewVehicle = new javax.swing.JLabel();
        vehicleNumber = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        seatsNumber = new javax.swing.JLabel();
        seat = new javax.swing.JTextField();
        vehicleType = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        whoDriver = new javax.swing.JLabel();
        driver = new javax.swing.JComboBox<>();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 740));
        getContentPane().setLayout(null);

        header.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        Bato.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        Bato.setText("Bato+");
        Bato.setMaximumSize(new java.awt.Dimension(117, 47));
        Bato.setMinimumSize(new java.awt.Dimension(117, 47));

        profile.setBackground(new java.awt.Color(244, 244, 244));
        profile.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        profile.setForeground(new java.awt.Color(102, 102, 102));
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile.png"))); // NOI18N
        profile.setBorder(null);
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(Bato, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 979, Short.MAX_VALUE)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo)
                            .addComponent(Bato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))))
        );

        getContentPane().add(header);
        header.setBounds(0, 0, 1280, 95);

        AdminDashboard.setBackground(new java.awt.Color(255, 255, 255));
        AdminDashboard.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        AdminDashboard.setText("Admin Dashboard");
        AdminDashboard.setMaximumSize(new java.awt.Dimension(356, 47));
        AdminDashboard.setMinimumSize(new java.awt.Dimension(356, 47));
        getContentPane().add(AdminDashboard);
        AdminDashboard.setBounds(40, 120, 250, 50);

        intro.setBackground(new java.awt.Color(153, 153, 153));
        intro.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        intro.setForeground(new java.awt.Color(153, 153, 153));
        intro.setText("Manage vehicles, routes, trips, and users");
        getContentPane().add(intro);
        intro.setBounds(40, 160, 290, 20);

        vehicles.setBackground(new java.awt.Color(244, 244, 244));
        vehicles.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        vehicles.setForeground(new java.awt.Color(0, 0, 204));
        vehicles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/selectedVehicle.png"))); // NOI18N
        vehicles.setText("Vehicles");
        vehicles.setBorder(null);
        vehicles.setBorderPainted(false);
        vehicles.setContentAreaFilled(false);
        getContentPane().add(vehicles);
        vehicles.setBounds(30, 193, 110, 40);

        routes.setBackground(new java.awt.Color(244, 244, 244));
        routes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        routes.setForeground(new java.awt.Color(102, 102, 102));
        routes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/routeIcon.png"))); // NOI18N
        routes.setText("Routes");
        routes.setBorder(null);
        routes.setBorderPainted(false);
        routes.setContentAreaFilled(false);
        getContentPane().add(routes);
        routes.setBounds(140, 193, 110, 40);

        trips.setBackground(new java.awt.Color(244, 244, 244));
        trips.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        trips.setForeground(new java.awt.Color(102, 102, 102));
        trips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tripIcon.png"))); // NOI18N
        trips.setText("Trips");
        trips.setBorder(null);
        trips.setBorderPainted(false);
        trips.setContentAreaFilled(false);
        getContentPane().add(trips);
        trips.setBounds(250, 193, 110, 40);

        users.setBackground(new java.awt.Color(244, 244, 244));
        users.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        users.setForeground(new java.awt.Color(102, 102, 102));
        users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userIcon.png"))); // NOI18N
        users.setText("Users");
        users.setBorder(null);
        users.setBorderPainted(false);
        users.setContentAreaFilled(false);
        getContentPane().add(users);
        users.setBounds(360, 193, 110, 40);

        notifications.setBackground(new java.awt.Color(244, 244, 244));
        notifications.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        notifications.setForeground(new java.awt.Color(102, 102, 102));
        notifications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/notifIcon.png"))); // NOI18N
        notifications.setText("Notifications");
        notifications.setBorder(null);
        notifications.setBorderPainted(false);
        notifications.setContentAreaFilled(false);
        getContentPane().add(notifications);
        notifications.setBounds(470, 193, 110, 40);

        separator.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(separator);
        separator.setBounds(30, 230, 1205, 20);

        VehicleManagement.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        VehicleManagement.setText("Vehicle Management");
        getContentPane().add(VehicleManagement);
        VehicleManagement.setBounds(50, 240, 240, 54);

        add.setBackground(new java.awt.Color(0, 0, 204));
        add.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("+ Add Vehicle");
        getContentPane().add(add);
        add.setBounds(1070, 240, 150, 40);

        form.setBackground(new java.awt.Color(255, 255, 255));
        form.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        form.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        AddNewVehicle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddNewVehicle.setText("Add New Vehicle");

        vehicleNumber.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        vehicleNumber.setText("Vehicle Number");

        number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        number.setText("######");
        number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        number.addActionListener(this::numberActionPerformed);

        seatsNumber.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        seatsNumber.setText("Number of Seats");

        seat.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        seat.setText("0");
        seat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        vehicleType.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        vehicleType.setText("Vehicle Type");

        type.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        type.setForeground(new java.awt.Color(51, 51, 51));
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        type.addActionListener(this::typeActionPerformed);

        whoDriver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        whoDriver.setText("Driver");

        driver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        driver.setForeground(new java.awt.Color(51, 51, 51));
        driver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        driver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        submit.setBackground(new java.awt.Color(0, 0, 204));
        submit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Add Vehicle");

        cancel.setBackground(new java.awt.Color(153, 153, 153));
        cancel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(this::cancelActionPerformed);

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vehicleNumber)
                    .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(seat)
                        .addComponent(AddNewVehicle, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formLayout.createSequentialGroup()
                            .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(seatsNumber, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(number, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)))
                .addGap(44, 44, 44)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vehicleType)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whoDriver)
                    .addComponent(driver, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(AddNewVehicle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(vehicleNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(vehicleType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(type)))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatsNumber)
                    .addComponent(whoDriver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(form);
        form.setBounds(60, 310, 1150, 260);

        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle", "Type", "Seats", "Driver", "Actions"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 620, 1150, 90);

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DashboardBackground.png"))); // NOI18N
        background.setFocusable(false);
        background.setMaximumSize(new java.awt.Dimension(1024, 640));
        background.setMinimumSize(new java.awt.Dimension(1024, 640));
        background.setPreferredSize(new java.awt.Dimension(1480, 1024));
        getContentPane().add(background);
        background.setBounds(0, 0, 1440, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VehicleManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddNewVehicle;
    private javax.swing.JLabel AdminDashboard;
    private javax.swing.JLabel Bato;
    private javax.swing.JLabel VehicleManagement;
    private javax.swing.JButton add;
    private javax.swing.JLabel background;
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> driver;
    private javax.swing.JPanel form;
    private javax.swing.JPanel header;
    private javax.swing.JLabel intro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton notifications;
    private javax.swing.JTextField number;
    private javax.swing.JButton profile;
    private javax.swing.JButton routes;
    private javax.swing.JTextField seat;
    private javax.swing.JLabel seatsNumber;
    private javax.swing.JSeparator separator;
    private javax.swing.JButton submit;
    private javax.swing.JButton trips;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JButton users;
    private javax.swing.JLabel vehicleNumber;
    private javax.swing.JLabel vehicleType;
    private javax.swing.JButton vehicles;
    private javax.swing.JLabel whoDriver;
    // End of variables declaration//GEN-END:variables
}
